### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by ThaDafinser**
I didnt read through the `ADD_FLAG` options yet...copied some of the `config.m4`

So i was able to compile it with this file and the guide https://wiki.php.net/internals/windows/stepbystepbuild

#1

### CODE REVIEW

**Comment by ThaDafinser** [comment]
Not updated with the latest changes (new .c and .h file)

Just with the working commit you gave me

**Comment by gkralik** [comment]
Cool. I think SAP Note 1056696 has information on how to compile for windows (needed compiler and linker flags).

**Comment by ThaDafinser** [comment]
Found this there 

Windows (x86, 32 Bit)
```
cl -DBCDASM -nologo -Od -Ob1 -fp:strict -Gy -GF -EHs -Z7 -W3 -Wp64 -D_X86_ -DWIN32 -DSAPwithUNICODE -DUNICODE -D_UNICODE -MD -D_AFXDLL -FR -J -RTC1 -D_CRT_NON_CONFORMING_SWPRINTFS -D_CRT_SECURE_NO_DEPRECATE D_CRT_NONSTDC_NO_DEPRECATE -DSAPonNT -c /EHc- /TP <Programm>.cpp

link -nologo /NXCOMPAT -STACK:0x800000 ole32.lib rpcrt4.lib oleaut32.lib
oledb.lib uuid.lib kernel32.lib advapi32.lib user32.lib gdi32.lib winspool.lib ws2_32.lib
Iphlpapi.lib netapi32.lib comdlg32.lib shell32.lib dbghelp.lib version.lib mpr.lib secur32.lib -
OPT:REF -LARGEADDRESSAWARE -subsystem:console -out:<Programm>.exe <Programm>.obj sapnwrfc.lib
libsapucum.lib [und eventuell sapdecfICUlib.lib]
```

Windows (x86, 64 Bit)
```
Ersetzen Sie im Beispiel für x86, 32 Bit "-D_X86_ -DWIN32" durch "-D_AMD64_ -
DWIN64" und geben Sie als zusätzliche Linker-Option /MACHINE:AMD64 an.
```

**Comment by ThaDafinser** [comment]
Works now with current master. Also the flags were updated from the docs

**Comment by gkralik** [comment]
What about the linker flags given in the note?

**Pull request merged**
