### PR TITLE
windows build instructions

### PR DESCRIPTION
**Pull request by ThaDafinser**
#8 

Shall i split it to a seperate build readme?

### CODE REVIEW

**Comment by gkralik** [comment]
That was quick :smile: 

Yes, split it out to something like docs/build_on_windows.md and reference it from the README -> Building -> Windows section. That way the readme is not so bloated and all detailed documentation is in the docs folder.

**Comment by ThaDafinser** [comment]
Yeah, want to get it done, so i can move to PHP7 production finally...

**Comment by ThaDafinser** [comment]
@gkralik here you go

**Comment by gkralik** [comment]
Thanks. I merged it into my documentation work. Will update at the weekend.

**Pull request closed without merging**
